### ISSUE TITLE
Doesn't run on Bluemix

### ISSUE THREAD

**Issue by dotnsf** [dotnsf/hashchainsolo#13]
Following error triggered **only when run on Bluemix** at :  var nano = require( 'nano' )( 'https://xxxx-bluemix:yyyy@xxxx-bluemix.cloudant.com' ); 

  2018-09-11T10:49:28.08+0900 [APP/PROC/WEB/0] OUT > node app.js
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] OUT db url=https://xxxx-bluemix:yyyy@xxxx-bluemix.cloudant.com
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR /home/vcap/app/node_modules/nano/lib/nano.js:83
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     return function(err, response = { statusCode: 500 }, body = '') {
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR                                   ^
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR SyntaxError: Unexpected token =
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at exports.runInThisContext (vm.js:53:16)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:373:25)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:416:10)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Module.load (module.js:343:32)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Function.Module._load (module.js:300:12)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Module.require (module.js:353:17)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at require (internal/module.js:12:17)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Object.<anonymous> (/home/vcap/app/app.js:24:14)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Module._compile (module.js:409:26)
   2018-09-11T10:49:28.39+0900 [APP/PROC/WEB/0] ERR     at Object.Module._extensions..js (module.js:416:10)
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Linux 4.4.0-109-generic
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! node v4.8.7
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! npm  v2.15.11
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! code ELIFECYCLE
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! hashchainsolo@0.0.2 start: `node app.js`
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Exit status 1
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! 
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Failed at the hashchainsolo@0.0.2 start script 'node app.js'.
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! This is most likely a problem with the hashchainsolo package,
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! not with npm itself.
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Tell the author that this fails on your system:
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR!     node app.js
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! You can get information on how to open an issue for this project with:
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR!     npm bugs hashchainsolo
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! Or if that isn't available, you can get their info via:
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! 
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR!     npm owner ls hashchainsolo
   2018-09-11T10:49:28.41+0900 [APP/PROC/WEB/0] ERR npm ERR! There is likely additional logging output above.
   2018-09-11T10:49:28.42+0900 [APP/PROC/WEB/0] ERR npm ERR! Please include the following file with any support request:
   2018-09-11T10:49:28.42+0900 [APP/PROC/WEB/0] ERR npm ERR!     /home/vcap/app/npm-debug.log
   2018-09-11T10:49:28.43+0900 [APP/PROC/WEB/0] OUT Exit status 1
   2018-09-11T10:49:28.43+0900 [CELL/0] OUT Exit status 0

**Comment by dotnsf** [comment]
https://github.com/apache/couchdb-nano/issues/122

**Comment by dotnsf** [comment]
Workaround found: Use https://www.npmjs.com/package/@cloudant/cloudant instead.

**Comment by dotnsf** [comment]
Workaround found.

**Comment by mumeshr** [comment]
I need to work with attachments and cloudant/cloudant package points to nano and same code works in local, but failing in Bluemix
